steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sample-api'
      - '-f'
      - 'Sample_API/Sample_API.API/Dockerfile'  # Update the path to your Dockerfile
      - '.'  # Set the build context to the root directory

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sample-api']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sample-net-api'  # Update with your service name
      - '--image=gcr.io/$PROJECT_ID/sample-api'
      - '--region=us-central1'
      - '--platform=managed'
      # Additional deployment options go here

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export REVISION_NAME=$(gcloud run revisions list --platform=managed --service=sample-net-api --format="value(metadata.name)")
        export REVISION_URL=$(gcloud run services describe sample-net-api --platform=managed --region=us-central1 --format="value(status.url)")
        export REVISION_TAG=$(echo $REVISION_URL | awk -F/ '{print $NF}')
        gcloud run revisions update $REVISION_NAME --platform=managed --service=sample-net-api --region=us-central1 --update-labels=revision-tag=$REVISION_TAG

images:
  - 'gcr.io/$PROJECT_ID/sample-api'
