steps:
  - id: 'Build Docker image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - '_CONNECTION_STRING=${_CONNECTION_STRING}'  # Pass the substitution variable as a build argument
      - '-t'
      - 'gcr.io/$PROJECT_ID/sample-api'
      - '-f'
      - 'Sample_API/Sample_API.API/Dockerfile'  # Update the path to your Dockerfile
      - '.'  # Set the build context to the root directory
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'  # Explicitly set the build region to us-central1

  - id: 'Push to Artifact Registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sample-api']

  - id: 'Deploy to Cloud Run)'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sample-api-prod'  # Update with your service name
      - '--image=gcr.io/$PROJECT_ID/sample-api'
      - '--region=us-central1'  # Explicitly set the region to us-central1
      - '--platform=managed'

options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/sample-api-pool' # specify pool to use for builds - region has to match build region

substitutions:
    _DEV_SERVICE_URL: 'https://sample-api-prod-ccezryvcoa-uc.a.run.app'
    _ENVIRONMENT: 'Production' # Expose substitution variable for use in Slack notification template

images:
  - 'gcr.io/$PROJECT_ID/sample-api'
