steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=sample-api-cloud-build-service-account-key > /workspace/service-account-key.json

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=/workspace/service-account-key.json
        gcloud sql instances patch sample-api --assign-ip
        gcloud sql instances patch sample-api --authorized-networks=10.128.0.0/20

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sample-api'
      - '-f'
      - 'Sample_API/Sample_API.API/Dockerfile'  # Update the path to your Dockerfile
      - '.'  # Set the build context to the root directory

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sample-api']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sample-api-dev'  # Update with your service name
      - '--image=gcr.io/$PROJECT_ID/sample-api'
      - '--region=us-central1'
      - '--platform=managed'
      - '--tag=dev-$SHORT_SHA'  # Tag revisions with a unique "revision URL tags"

substitutions:
    _DEV_SERVICE_URL: 'https://dev-${SHORT_SHA}---sample-api-dev-ccezryvcoa-uc.a.run.app/'
    _ENVIRONMENT: 'Development'

images:
  - 'gcr.io/$PROJECT_ID/sample-api'
